### ISSUE TITLE
Can't install with Plug

### ISSUE THREAD

**Issue by ovidius72** [judaew/ronny.nvim#1]
Trying to install with Plug when I do `require('ronny').setup({})` I get this error:
<img width="1458" alt="image" src="https://github.com/judaew/ronny.nvim/assets/3592928/d530447a-3111-4c74-ac23-807e046b0109">

Thanks.

**Comment by judaew** [comment]
Thanks for reporting the problem. Please try executing `:PlugUpdate`, and then attempt it once more.

**Comment by ovidius72** [comment]
> Thanks for reporting the problem. Please try executing `:PlugUpdate`, and then attempt it once more.

Thank you. It works now.
